import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "cattle-growth-formula",
    name: "Premium Cattle Growth Formula",
    description: "High-protein feed designed to promote optimal growth and development in cattle of all ages.",
    price: 24.99,
    image: "/images/cattle-growth-formula.jpg",
    animalType: "Cattle",
    benefits: [
      "Enhanced muscle development",
      "Improved weight gain",
      "Supports immune system health",
      "Balanced mineral content for bone development",
    ],
    sizes: ["25 lb bag", "50 lb bag", "1 ton bulk"],
  },
  {
    id: "dairy-production-blend",
    name: "Dairy Production Blend",
    description: "Specially formulated to increase milk production and improve milk quality in dairy cows.",
    price: 29.99,
    image: "/images/dairy-production-blend.jpg",
    animalType: "Cattle",
    benefits: [
      "Increases milk production",
      "Improves milk fat content",
      "Supports udder health",
      "Enhances reproductive performance",
    ],
    sizes: ["25 lb bag", "50 lb bag", "1 ton bulk"],
  },
  {
    id: "poultry-layer-feed",
    name: "Complete Layer Feed",
    description: "Nutritionally balanced feed for laying hens to promote egg production and shell quality.",
    price: 19.99,
    image: "/images/poultry-layer-feed.jpg",
    animalType: "Poultry",
    benefits: [
      "Increases egg production",
      "Improves shell strength",
      "Enhances yolk color",
      "Supports overall bird health",
    ],
    sizes: ["10 lb bag", "25 lb bag", "50 lb bag"],
  },
  {
    id: "broiler-starter",
    name: "Broiler Starter Feed",
    description: "High-protein feed designed for the first stage of broiler chicken growth.",
    price: 22.99,
    image: "/images/broiler-starter.jpg",
    animalType: "Poultry",
    benefits: [
      "Rapid early growth",
      "Optimal feather development",
      "Strong skeletal formation",
      "Enhanced immune function",
    ],
    sizes: ["10 lb bag", "25 lb bag", "50 lb bag"],
  },
  {
    id: "swine-grower",
    name: "Swine Grower Feed",
    description: "Balanced nutrition for growing pigs to support healthy weight gain and muscle development.",
    price: 21.99,
    image: "/images/swine-grower.jpg",
    animalType: "Swine",
    benefits: [
      "Efficient feed conversion",
      "Optimal lean muscle growth",
      "Reduced fat deposition",
      "Supports digestive health",
    ],
    sizes: ["25 lb bag", "50 lb bag", "1 ton bulk"],
  },
  {
    id: "sheep-complete",
    name: "Complete Sheep Feed",
    description: "All-in-one nutritional solution for sheep of all ages and production stages.",
    price: 23.99,
    image: "/images/sheep-complete.jpg",
    animalType: "Sheep",
    benefits: [
      "Supports wool quality and growth",
      "Enhances reproductive performance",
      "Balanced copper levels for safety",
      "Promotes overall health",
    ],
    sizes: ["25 lb bag", "50 lb bag"],
  },
  {
    id: "horse-performance",
    name: "Equine Performance Blend",
    description: "Premium feed formulated for active and performance horses with higher energy requirements.",
    price: 34.99,
    image: "/images/horse-performance.jpg",
    animalType: "Horses",
    benefits: [
      "Sustained energy release",
      "Muscle recovery support",
      "Joint health ingredients",
      "Enhanced coat condition",
    ],
    sizes: ["25 lb bag", "50 lb bag"],
  },
  {
    id: "goat-dairy-feed",
    name: "Dairy Goat Feed",
    description: "Specialized nutrition for lactating dairy goats to maximize milk production and quality.",
    price: 26.99,
    image: "/images/goat-dairy-feed.jpg",
    animalType: "Sheep",
    benefits: [
      "Increases milk yield",
      "Improves milk composition",
      "Supports lactation persistence",
      "Balanced calcium for lactating does",
    ],
    sizes: ["25 lb bag", "50 lb bag"],
  },
]
